name: Android CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up Azul Zulu JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
